version: "3.7"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000 --settings=app.settings-docker
    volumes:
      - .:/code
      - ./data/data:/home
      - ./data/private:/private-media
    ports:
      - "8000:8000"
    depends_on:
      - db
