# Generated by Django 3.1.1 on 2022-04-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.AddField(
            model_name='todo',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
