# Generated by Django 3.1.1 on 2022-05-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_gallery_wallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('todos', "To do's"), ('files', 'Files'), ('notes', 'Notes'), ('events', 'Events'), ('images', 'Images'), ('snippet', 'Code snippets'), ('upload', 'Upload')], max_length=8, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField()),
                ('refresh_interval', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
