# Generated by Django 3.1.1 on 2022-05-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.UniqueConstraint(condition=models.Q(active=True), fields=('active',), name='Unique constraint for active gallery'),
        ),
    ]
