# Generated by Django 3.1.1 on 2021-10-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('todos', "To do's"), ('files', 'Files'), ('notes', 'Notes')], max_length=8, unique=True)),
                ('title', models.CharField(max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
