# Generated by Django 3.1.1 on 2021-09-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('position',)},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('activate_date',)},
        ),
    ]
