# Generated by Django 3.1.1 on 2021-07-31 16:42

from django.db import migrations, models
import private_files.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', private_files.models.fields.PrivateFileField(upload_to='private/')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
