# Generated by Django 3.1.1 on 2022-01-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20211228_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='refresh_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
