# Generated by Django 3.1.1 on 2022-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_widget_refresh_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('todos', "To do's"), ('files', 'Files'), ('notes', 'Notes'), ('events', 'Events'), ('images', 'Images'), ('dates', 'Historical dates')], max_length=8, unique=True),
        ),
    ]
