# Generated by Django 3.1.1 on 2022-01-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20220103_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('plain_text', 'Plain text'), ('markdown', 'Markdown')], default='plain_text', max_length=16),
        ),
    ]
