# Generated by Django 3.1.1 on 2022-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_auto_20220103_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
