# Generated by Django 3.1.1 on 2022-01-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_codesnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('todos', "To do's"), ('files', 'Files'), ('notes', 'Notes'), ('events', 'Events'), ('images', 'Images'), ('dates', 'Historical dates'), ('snippet', 'Code snippets')], max_length=8, unique=True),
        ),
    ]
