# Generated by Django 3.1.1 on 2022-03-09 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_auto_20220307_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatefile',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='privateimage',
            name='tags',
        ),
    ]
