# Generated by Django 3.1.1 on 2022-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_auto_20220309_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='HistoricalDate',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='PrivateFile',
        ),
        migrations.DeleteModel(
            name='PrivateImage',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.AlterField(
            model_name='widget',
            name='type',
            field=models.CharField(choices=[('todos', "To do's"), ('files', 'Files'), ('notes', 'Notes'), ('events', 'Events'), ('images', 'Images'), ('snippet', 'Code snippets'), ('upload', 'Upload')], max_length=8, unique=True),
        ),
    ]
