# Generated by Django 3.1.1 on 2022-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0011_auto_20220309_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
