# Generated by Django 3.1.1 on 2022-05-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_auto_20220424_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Wallpaper',
        ),
    ]
