# Generated by Django 3.1.1 on 2022-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_delete_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
