# Generated by Django 3.1.1 on 2022-04-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_delete_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
