# Generated by Django 3.1.1 on 2022-05-08 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_auto_20220506_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
