# Generated by Django 3.1.1 on 2022-04-21 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0014_delete_codesnippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateFile',
        ),
        migrations.DeleteModel(
            name='PrivateImage',
        ),
    ]
